README.md

Just finished to watched again Etienne Chouard interview. He strongly recommended those books. Could be great to store them here.

Add Etienne Chouard books

---

README.md

Bonjour,
ajout des livres recommandés par Marc Eichinger.
Bonne journée,
Ghislain

add Marc Eichinger

---

README.md

Salut,
ajout des interviews du 8 septembre 2020 : 
- Julia Cagé
- Alexandre Langlois et Noam Anouar
Bonne journée,
Ghislain

Interviews du 8 septembre 2020

---

README.md

Bonjour,
ajout de l'interview de Christophe Deloire 
ajout de lien peertube
Bonne journée,
Ghislain

ajout de l'interview de Christophe Deloire 

---

README.md

Bonsoir,
ajout de l'interview de Renaud Piarroux  (Tolkien oO :D )
ajout des liens peertube pour Béatrice Brugère et Christophe Deloire
Ghislain

Interview de Renaud Piarroux 

---

README.md

Bonjour Killkitten,
au menu :
- Ajout de l'interview de Raphaël Rossello
- Ajout de 3 liens peertube
J'ai ajouté le livre de M. Rosselo dans la liste avec une explication. Il a demandé s'il pouvait le conseiller et "Sky" a refusé contrairement à d'autres invités.
Bonne journée,
Ghislain

Ajout de l'interview de Raphaël Rossello

---

README.md

Bonjour,
ajout de l'interview de Guillaume Meurice.
Bonne journée et bon week-end,
Ghislain

Ajout de Guillaume Meurice

---

README.md

Bonjour,
liens des sites et correction du nom NextInpact pour l'interview de Marc Rees
Bonne journée

Correction et liens pour Marc Rees

---

README.md

Bonjour,
ajout de l'interview de Philippe Corcuff.
Bonne journée,
Ghislain

66% d'abstention : la grande confusion ? Philippe Corcuff

---

README.md

Bonjour,
ajout de "Le hacking au XXIe siècle ? Zax et Doomer" avec les références.
Par contre j'ai pas encore fini "Ambassadeur de Chine sans filtre ? Lu Shaye", donc pas de références.
Bonne journée,
Ghislain

Le hacking au XXIe siècle ? Zax et Doomer

---

README.md

Bonjour,
ajout de l'interview de Clément Viktorovitch.
Bonne journée,
Ghislain

ajout de Clément Viktorovitch

---

README.md

Bonjour @Killkitten ,
il y a plusieurs références durant l'interview.  J'en ai probablement loupé une ou deux.
Il est fait référence à Jacques Blamont mais le nom du livre n'est pas donné.
Bonne journée et week-end,
Ghislain

Etienne Klein

---

README.md

Bonjour! 
Je ne me suis pas retapé toute l'interview et donc je n'ai mis que les dernières suggestions en fin de vidéo.

Ajout Eric Zemmour

---

README.md

Bonjour,
ajout de Éviter l’effondrement ? Jean-Marc Jancovici et Laurent Morel.
Bonne fin de semaine,
Ghislain

Ajout de Éviter l’effondrement ? Jean-Marc Jancovici et Laurent Morel

---

README.md

Bonjour,
ajout des références de l'interview "coup d'état numérique, la matrice ? Christophe Deloire"
Bonne journée,
Ghislain

Ajout de Christophe Deloire

---

README.md

Bonjour,
j'ai ajouté l'interview de Nicolas Meilhan et Francis Perrin.
Par contre j'ai pas encore regardé la dernière de Mélenchon.
Bon week-end,
Ghislain

Nicolas Meilhan et Francis Perrin

---

README.md

Bonjour,
J'ai ajouté les livres et auteurs mentionnés dans l'interview du 4 mai 2022 (Pascal Boniface).
Salutations.

ajout de Pascal Boniface

---

README.md

Bonjour,
proposition des références de l'interview de Emma Haziza
Bonne journée,
Ghislain

Ajout de Emma Haziza

---

README.md

Bonjour,
ajout de l'interview d'August Cole.
Bonne journée,
Ghislain

Ajout de August Cole

---

README.md

Bonjour,
Proposition d'ajout d'une interview du Professeur Renaud Piarroux
Cordialement,
A.C.

Désinformation en temps d'épidémie ? Pr Renaud Piarroux

---

README.md

Ajout de l'interview de Flore Vasseur

En bande organisée ? Flore Vasseur 

---

README.md

Bonjour,
Petite maj jusqu'à l'épisode du 28 novembre 2023.
Bonne journée 😃

mise à jour jusqu'au 15/09/23
